<a href="https://colab.research.google.com/github/karthickow/ai/blob/main/tensorflow_sample.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [40]:
import tensorflow as tf
import numpy as np

print(tf.__version__)

a = tf.constant([1, 2, 3, 5])
b = tf.constant([5, 2, 3, 4])

res = tf.multiply(a, b)
#print(tf.rank(a))
#print(res)

array_2d_1 = np.array(np.arange(9).reshape(3, 3), dtype='float')
array_2d_2 = np.array(np.arange(9,18).reshape(3,3), dtype='float')


print(array_2d_1)
print(array_2d_2)
print(array_2d_1.ndim)
print(array_2d_1.shape)
print(array_2d_1.dtype)

tensor_2d_1 = tf.convert_to_tensor(array_2d_1)
tensor_2d_2 = tf.convert_to_tensor(array_2d_2)

print(tensor_2d_1)
print('\nMatrix addition\n\n', tf.add(tensor_2d_1, tensor_2d_2))
print('\nMatrix multiplication\n\n', tf.matmul(tensor_2d_1, tensor_2d_2))
print('\nMatrix determinant\n\n', tf.linalg.det(tensor_2d_1))

2.14.0
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
[[ 9. 10. 11.]
 [12. 13. 14.]
 [15. 16. 17.]]
2
(3, 3)
float64
tf.Tensor(
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]], shape=(3, 3), dtype=float64)

Matrix addition

 tf.Tensor(
[[ 9. 11. 13.]
 [15. 17. 19.]
 [21. 23. 25.]], shape=(3, 3), dtype=float64)

Matrix multiplication

 tf.Tensor(
[[ 42.  45.  48.]
 [150. 162. 174.]
 [258. 279. 300.]], shape=(3, 3), dtype=float64)

Matrix determinant

 tf.Tensor(0.0, shape=(), dtype=float64)
